// Code generated by ent, DO NOT EDIT.

package entity

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/dsha256/packer-pro/internal/entity/size"
)

// Size is the model entity for the Size schema.
type Size struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Size holds the value of the "size" field.
	Size         int `json:"size,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Size) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case size.FieldID, size.FieldSize:
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Size fields.
func (s *Size) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case size.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			s.ID = int(value.Int64)
		case size.FieldSize:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field size", values[i])
			} else if value.Valid {
				s.Size = int(value.Int64)
			}
		default:
			s.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Size.
// This includes values selected through modifiers, order, etc.
func (s *Size) Value(name string) (ent.Value, error) {
	return s.selectValues.Get(name)
}

// Update returns a builder for updating this Size.
// Note that you need to call Size.Unwrap() before calling this method if this Size
// was returned from a transaction, and the transaction was committed or rolled back.
func (s *Size) Update() *SizeUpdateOne {
	return NewSizeClient(s.config).UpdateOne(s)
}

// Unwrap unwraps the Size entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (s *Size) Unwrap() *Size {
	_tx, ok := s.config.driver.(*txDriver)
	if !ok {
		panic("entity: Size is not a transactional entity")
	}
	s.config.driver = _tx.drv
	return s
}

// String implements the fmt.Stringer.
func (s *Size) String() string {
	var builder strings.Builder
	builder.WriteString("Size(")
	builder.WriteString(fmt.Sprintf("id=%v, ", s.ID))
	builder.WriteString("size=")
	builder.WriteString(fmt.Sprintf("%v", s.Size))
	builder.WriteByte(')')
	return builder.String()
}

// Sizes is a parsable slice of Size.
type Sizes []*Size
