// Code generated by ent, DO NOT EDIT.

package entity

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/dsha256/packer-pro/internal/entity/predicate"
	"github.com/dsha256/packer-pro/internal/entity/size"
)

// SizeUpdate is the builder for updating Size entities.
type SizeUpdate struct {
	config
	hooks    []Hook
	mutation *SizeMutation
}

// Where appends a list predicates to the SizeUpdate builder.
func (su *SizeUpdate) Where(ps ...predicate.Size) *SizeUpdate {
	su.mutation.Where(ps...)
	return su
}

// SetSize sets the "size" field.
func (su *SizeUpdate) SetSize(i int) *SizeUpdate {
	su.mutation.ResetSize()
	su.mutation.SetSize(i)
	return su
}

// SetNillableSize sets the "size" field if the given value is not nil.
func (su *SizeUpdate) SetNillableSize(i *int) *SizeUpdate {
	if i != nil {
		su.SetSize(*i)
	}
	return su
}

// AddSize adds i to the "size" field.
func (su *SizeUpdate) AddSize(i int) *SizeUpdate {
	su.mutation.AddSize(i)
	return su
}

// Mutation returns the SizeMutation object of the builder.
func (su *SizeUpdate) Mutation() *SizeMutation {
	return su.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (su *SizeUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, su.sqlSave, su.mutation, su.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (su *SizeUpdate) SaveX(ctx context.Context) int {
	affected, err := su.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (su *SizeUpdate) Exec(ctx context.Context) error {
	_, err := su.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (su *SizeUpdate) ExecX(ctx context.Context) {
	if err := su.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (su *SizeUpdate) check() error {
	if v, ok := su.mutation.Size(); ok {
		if err := size.SizeValidator(v); err != nil {
			return &ValidationError{Name: "size", err: fmt.Errorf(`entity: validator failed for field "Size.size": %w`, err)}
		}
	}
	return nil
}

func (su *SizeUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := su.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(size.Table, size.Columns, sqlgraph.NewFieldSpec(size.FieldID, field.TypeInt))
	if ps := su.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := su.mutation.Size(); ok {
		_spec.SetField(size.FieldSize, field.TypeInt, value)
	}
	if value, ok := su.mutation.AddedSize(); ok {
		_spec.AddField(size.FieldSize, field.TypeInt, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, su.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{size.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	su.mutation.done = true
	return n, nil
}

// SizeUpdateOne is the builder for updating a single Size entity.
type SizeUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SizeMutation
}

// SetSize sets the "size" field.
func (suo *SizeUpdateOne) SetSize(i int) *SizeUpdateOne {
	suo.mutation.ResetSize()
	suo.mutation.SetSize(i)
	return suo
}

// SetNillableSize sets the "size" field if the given value is not nil.
func (suo *SizeUpdateOne) SetNillableSize(i *int) *SizeUpdateOne {
	if i != nil {
		suo.SetSize(*i)
	}
	return suo
}

// AddSize adds i to the "size" field.
func (suo *SizeUpdateOne) AddSize(i int) *SizeUpdateOne {
	suo.mutation.AddSize(i)
	return suo
}

// Mutation returns the SizeMutation object of the builder.
func (suo *SizeUpdateOne) Mutation() *SizeMutation {
	return suo.mutation
}

// Where appends a list predicates to the SizeUpdate builder.
func (suo *SizeUpdateOne) Where(ps ...predicate.Size) *SizeUpdateOne {
	suo.mutation.Where(ps...)
	return suo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (suo *SizeUpdateOne) Select(field string, fields ...string) *SizeUpdateOne {
	suo.fields = append([]string{field}, fields...)
	return suo
}

// Save executes the query and returns the updated Size entity.
func (suo *SizeUpdateOne) Save(ctx context.Context) (*Size, error) {
	return withHooks(ctx, suo.sqlSave, suo.mutation, suo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (suo *SizeUpdateOne) SaveX(ctx context.Context) *Size {
	node, err := suo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (suo *SizeUpdateOne) Exec(ctx context.Context) error {
	_, err := suo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (suo *SizeUpdateOne) ExecX(ctx context.Context) {
	if err := suo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (suo *SizeUpdateOne) check() error {
	if v, ok := suo.mutation.Size(); ok {
		if err := size.SizeValidator(v); err != nil {
			return &ValidationError{Name: "size", err: fmt.Errorf(`entity: validator failed for field "Size.size": %w`, err)}
		}
	}
	return nil
}

func (suo *SizeUpdateOne) sqlSave(ctx context.Context) (_node *Size, err error) {
	if err := suo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(size.Table, size.Columns, sqlgraph.NewFieldSpec(size.FieldID, field.TypeInt))
	id, ok := suo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`entity: missing "Size.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := suo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, size.FieldID)
		for _, f := range fields {
			if !size.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("entity: invalid field %q for query", f)}
			}
			if f != size.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := suo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := suo.mutation.Size(); ok {
		_spec.SetField(size.FieldSize, field.TypeInt, value)
	}
	if value, ok := suo.mutation.AddedSize(); ok {
		_spec.AddField(size.FieldSize, field.TypeInt, value)
	}
	_node = &Size{config: suo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, suo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{size.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	suo.mutation.done = true
	return _node, nil
}
