-- create "sizes" table
CREATE TABLE "sizes" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "size" bigint NOT NULL,
  PRIMARY KEY ("id")
);
-- create index "sizes_size_key" to table: "sizes"
CREATE UNIQUE INDEX "sizes_size_key" ON "sizes" ("size");
