// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// SizesColumns holds the columns for the "sizes" table.
	SizesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "size", Type: field.TypeInt, Unique: true},
	}
	// SizesTable holds the schema information for the "sizes" table.
	SizesTable = &schema.Table{
		Name:       "sizes",
		Columns:    SizesColumns,
		PrimaryKey: []*schema.Column{SizesColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		SizesTable,
	}
)

func init() {
}
